"""In-app notifications generated by claims, pickups and ratings."""

from httpx import AsyncClient

from tests.conftest import Account
from tests.test_listings import post_listing


async def test_claim_notifies_the_host(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    notes = (await client.get("/notifications", headers=organizer.headers)).json()
    assert notes["unread_count"] == 1
    assert "claimed" in notes["items"][0]["message"]
    assert notes["items"][0]["listing_id"] == listing["id"]


async def test_pickup_notifies_the_recipient(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    claim = (
        await client.post(
            "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
        )
    ).json()
    await client.post(f"/claims/{claim['id']}/pickup", headers=organizer.headers)

    notes = (await client.get("/notifications", headers=recipient.headers)).json()
    assert any("Pickup confirmed" in n["message"] for n in notes["items"])


async def test_rating_notifies_the_host(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    claim = (
        await client.post(
            "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
        )
    ).json()
    await client.post(f"/claims/{claim['id']}/pickup", headers=organizer.headers)
    await client.post(
        f"/claims/{claim['id']}/rate", headers=recipient.headers, json={"stars": 5}
    )

    notes = (await client.get("/notifications", headers=organizer.headers)).json()
    assert any("rated you 5" in n["message"] for n in notes["items"])


async def test_mark_read_clears_unread(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    before = (await client.get("/notifications", headers=organizer.headers)).json()
    assert before["unread_count"] >= 1

    r = await client.post("/notifications/read", headers=organizer.headers)
    assert r.status_code == 204

    after = (await client.get("/notifications", headers=organizer.headers)).json()
    assert after["unread_count"] == 0


async def test_notifications_are_per_user(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )
    # The host got notified; the recipient who claimed did not.
    mine = (await client.get("/notifications", headers=recipient.headers)).json()
    assert mine["unread_count"] == 0


async def test_delete_removes_one_notification(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    before = (await client.get("/notifications", headers=organizer.headers)).json()
    assert len(before["items"]) >= 1
    target = before["items"][0]["id"]

    r = await client.delete(f"/notifications/{target}", headers=organizer.headers)
    assert r.status_code == 204

    after = (await client.get("/notifications", headers=organizer.headers)).json()
    assert target not in [n["id"] for n in after["items"]]
    assert len(after["items"]) == len(before["items"]) - 1


async def test_cannot_delete_someone_elses_notification(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    """Deleting by id alone would let anyone clear another user's feed."""
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    theirs = (await client.get("/notifications", headers=organizer.headers)).json()
    target = theirs["items"][0]["id"]

    r = await client.delete(f"/notifications/{target}", headers=recipient.headers)
    assert r.status_code == 404

    # Still there for its owner.
    after = (await client.get("/notifications", headers=organizer.headers)).json()
    assert target in [n["id"] for n in after["items"]]


async def test_clear_removes_every_notification(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    before = (await client.get("/notifications", headers=organizer.headers)).json()
    assert len(before["items"]) >= 1

    r = await client.delete("/notifications", headers=organizer.headers)
    assert r.status_code == 204

    after = (await client.get("/notifications", headers=organizer.headers)).json()
    assert after["items"] == []
    # The dot goes with them: an unread count outliving its rows would leave a
    # badge pointing at nothing, with no way to clear it.
    assert after["unread_count"] == 0


async def test_clear_leaves_other_users_alone(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    """Clearing is scoped by user_id, like deleting one is."""
    listing = await post_listing(client, organizer)
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )
    mine = (await client.get("/claims/mine", headers=recipient.headers)).json()
    claim_id = mine["items"][0]["id"]
    await client.post(f"/claims/{claim_id}/pickup", headers=organizer.headers)

    # The pickup notified the recipient; the claim notified the organizer.
    theirs = (await client.get("/notifications", headers=recipient.headers)).json()
    assert len(theirs["items"]) >= 1

    await client.delete("/notifications", headers=organizer.headers)

    still = (await client.get("/notifications", headers=recipient.headers)).json()
    assert len(still["items"]) == len(theirs["items"])


async def test_clear_when_there_is_nothing_is_not_an_error(
    client: AsyncClient, organizer: Account
) -> None:
    """Asking for an empty list and already having one is the same outcome."""
    r = await client.delete("/notifications", headers=organizer.headers)
    assert r.status_code == 204


async def test_delete_unknown_notification_is_404(
    client: AsyncClient, organizer: Account
) -> None:
    missing = "00000000-0000-0000-0000-000000000000"
    r = await client.delete(f"/notifications/{missing}", headers=organizer.headers)
    assert r.status_code == 404


# ---------------------------------------------------------------------------
# What the row is about — kind, and the listing it points at
# ---------------------------------------------------------------------------


async def test_each_event_records_what_kind_it_was(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    """The client picks an icon from this, so it must not be guessed from prose."""
    listing = await post_listing(client, organizer)
    claim = (
        await client.post(
            "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
        )
    ).json()
    await client.post(f"/claims/{claim['id']}/pickup", headers=organizer.headers)
    await client.post(
        f"/claims/{claim['id']}/rate", headers=recipient.headers, json={"stars": 5}
    )

    host = (await client.get("/notifications", headers=organizer.headers)).json()
    assert {n["kind"] for n in host["items"]} == {"claim", "rating"}

    theirs = (await client.get("/notifications", headers=recipient.headers)).json()
    assert [n["kind"] for n in theirs["items"]] == ["pickup"]


async def test_notification_carries_the_food_it_is_about(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    photo = "https://images.example.com/pizza.jpg"
    listing = await post_listing(client, organizer, photo_urls=[photo])
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    note = (await client.get("/notifications", headers=organizer.headers)).json()[
        "items"
    ][0]
    assert note["listing_title"] == "Leftover pizza"
    assert note["listing_photo_url"] == photo


async def test_a_listing_without_photos_still_renders(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    # The title comes back, the thumbnail is simply null — the row still has to
    # be renderable, since most posts have no photo.
    listing = await post_listing(client, organizer, photo_urls=[])
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    note = (await client.get("/notifications", headers=organizer.headers)).json()[
        "items"
    ][0]
    assert note["listing_title"] == "Leftover pizza"
    assert note["listing_photo_url"] is None


async def test_the_first_photo_is_the_thumbnail(
    client: AsyncClient, organizer: Account, recipient: Account
) -> None:
    first = "https://images.example.com/one.jpg"
    listing = await post_listing(
        client, organizer, photo_urls=[first, "https://images.example.com/two.jpg"]
    )
    await client.post(
        "/claims", headers=recipient.headers, json={"listing_id": listing["id"]}
    )

    note = (await client.get("/notifications", headers=organizer.headers)).json()[
        "items"
    ][0]
    assert note["listing_photo_url"] == first
