"""initial schema

Revision ID: 04dd91269988
Revises: 
Create Date: 2026-07-22 22:31:15.305093
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '04dd91269988'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('role', sa.Enum('organizer', 'recipient', name='userrole', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('dietary_prefs', sa.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email LIKE '%%@asu.edu'", name='ck_users_asu_email'),
    sa.CheckConstraint('email = lower(email)', name='ck_users_email_lowercase'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organizer_id', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_source', sa.Enum('voice', 'manual', name='descriptionsource', native_enum=False, create_constraint=True, length=10), server_default='manual', nullable=False),
    sa.Column('allergens', sa.Text(), nullable=True),
    sa.Column('dietary_tags', sa.ARRAY(sa.String(length=50)), server_default='{}', nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_remaining', sa.Integer(), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=False),
    sa.Column('building', sa.String(length=200), nullable=False),
    sa.Column('room', sa.String(length=100), nullable=True),
    sa.Column('placement_note', sa.Text(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('expiry_minutes', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'claimed', 'expired', 'cancelled', name='listingstatus', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expiry_minutes IN (15, 20, 30, 45, 60)', name='ck_listings_expiry_choice'),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name='ck_listings_lat_range'),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name='ck_listings_lng_range'),
    sa.CheckConstraint('quantity_remaining <= quantity_total', name='ck_listings_remaining_within_total'),
    sa.CheckConstraint('quantity_remaining >= 0', name='ck_listings_remaining_non_negative'),
    sa.CheckConstraint('quantity_total > 0', name='ck_listings_total_positive'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_listings_feed', 'listings', ['status', 'expires_at'], unique=False)
    op.create_index('ix_listings_location', 'listings', ['lat', 'lng'], unique=False)
    op.create_index('ix_listings_organizer', 'listings', ['organizer_id', 'created_at'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_id', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Enum('pending', 'picked_up', 'no_show', 'cancelled', name='claimstatus', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reservation_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND resolved_at IS NULL) OR (status <> 'pending' AND resolved_at IS NOT NULL)", name='ck_claims_resolved_at_matches_status'),
    sa.CheckConstraint('quantity > 0', name='ck_claims_quantity_positive'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'recipient_id', name='uq_claim_per_recipient')
    )
    op.create_index('ix_claims_listing', 'claims', ['listing_id'], unique=False)
    op.create_index('ix_claims_recipient', 'claims', ['recipient_id', 'claimed_at'], unique=False)
    op.create_index('ix_claims_reservation_expiry', 'claims', ['status', 'reservation_expires_at'], unique=False)
    op.create_table('listing_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('listing_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_listing_photos_position'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'position', name='uq_listing_photo_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing_photos')
    op.drop_index('ix_claims_reservation_expiry', table_name='claims')
    op.drop_index('ix_claims_recipient', table_name='claims')
    op.drop_index('ix_claims_listing', table_name='claims')
    op.drop_table('claims')
    op.drop_index('ix_listings_organizer', table_name='listings')
    op.drop_index('ix_listings_location', table_name='listings')
    op.drop_index('ix_listings_feed', table_name='listings')
    op.drop_table('listings')
    op.drop_table('users')
    # ### end Alembic commands ###
